#ifndef ACEGF_H
#define ACEGF_H

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "stdint.h"
#include "stdbool.h"
#include "stddef.h"

#define MlDsa44_PK_BYTES 1312

#define MlDsa44_SK_BYTES 2560

#define MlDsa44_SIG_BYTES 2420

#define MlDsa44_SEED_BYTES 32

// Encapsulation key (public) size in bytes — FIPS 203, ML-KEM-768.
#define MlKem768_EK_BYTES 1184

// Decapsulation key (secret) size in bytes — FIPS 203, ML-KEM-768.
#define MlKem768_DK_BYTES 2400

// Ciphertext size in bytes — FIPS 203, ML-KEM-768.
#define MlKem768_CT_BYTES 1088

// Shared-secret size in bytes.
#define MlKem768_SS_BYTES 32

// Expected byte length for a REV used in ZK-ACE (256-bit).
#define ZK_REV_BYTES 32

#define ACEGF_METHOD_GENERATE 1

#define ACEGF_METHOD_REKEY 3

#define ACEGF_METHOD_VIEW 4

typedef struct ACEGF_Call {
  int32_t method;
  const char *input_1;
  const char *input_2;
  const char *input_3;
} ACEGF_Call;

typedef struct ACEGF_Result {
  int32_t code;
  const char *data;
  uint64_t data_len;
  uint8_t reserved[8];
} ACEGF_Result;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Free a string returned by any acegf_* function
void acegf_free_string(char *ptr);

char *acegf_version(void);

// Generate a new wallet with passphrase
// Returns JSON: { mnemonic, solana_address, evm_address, bitcoin_address, cosmos_address, polkadot_address, xaddress, xidentity }
// or JSON: { error: true, message: "..." }
char *acegf_generate(const char *passphrase);

// Generate a new wallet with passphrase and optional secondary passphrase
char *acegf_generate_with_secondary(const char *passphrase, const char *secondary_passphrase);

// Restore wallet from mnemonic
// Returns JSON with wallet addresses or error
char *acegf_view_wallet(const char *mnemonic, const char *passphrase);

char *acegf_view_wallet_with_secondary(const char *mnemonic,
                                       const char *passphrase,
                                       const char *secondary_passphrase);

// Sign message - returns base64 signature on success, or "error:..." on failure
// curve: 0 = Ed25519, 1 = Secp256k1
char *acegf_sign_message(const char *mnemonic,
                         const char *passphrase,
                         const uint8_t *message,
                         size_t message_len,
                         uint32_t curve);

char *acegf_sign_message_with_secondary(const char *mnemonic,
                                        const char *passphrase,
                                        const char *secondary_passphrase,
                                        const uint8_t *message,
                                        size_t message_len,
                                        uint32_t curve);

char *acegf_xidentity_sign(const char *mnemonic,
                           const char *passphrase,
                           const uint8_t *message,
                           size_t message_len);

char *acegf_xidentity_verify(const char *xidentity_b64,
                             const uint8_t *message,
                             size_t message_len,
                             const uint8_t *signature,
                             size_t signature_len);

char *acegf_compute_dh_key(const char *mnemonic, const char *passphrase, const char *peer_pub_b64);

char *acegf_change_passphrase(const char *mnemonic,
                              const char *old_passphrase,
                              const char *new_passphrase);

// Encrypt data for a recipient's xidentity public key
// Returns JSON: { ephemeral_pub, encrypted_aes_key, iv, encrypted_data }
char *acegf_encrypt_for_xidentity(const char *recipient_xidentity_b64,
                                  const uint8_t *plaintext,
                                  size_t plaintext_len);

// Get the wallet's xkem (ML-KEM-768 encapsulation key) as a Base64
// C string, derived from `mnemonic + passphrase`.
//
// Parallel to `acegf_xidentity_sign` in that the wallet-side key is
// re-derived from the mnemonic; the returned string is the public
// encapsulation key that the wallet publishes as its post-quantum
// key-exchange identity.
//
// Returns a C string ("<base64>" on success, "error:..." on failure).
char *acegf_xkem_pubkey(const char *mnemonic, const char *passphrase);

// Encapsulate a shared secret against a recipient's published xkem.
//
// Parallel to `acegf_encrypt_for_xidentity`: no mnemonic required; the
// recipient's Base64 xkem is the only input beyond the returned JSON
// transport shape.
//
// Returns JSON C string on success:
//   `{ "shared_secret": "<b64>", "ciphertext": "<b64>" }`
// Returns `"error:..."` on failure.
char *acegf_encapsulate_for_xkem(const char *recipient_xkem_b64);

// Recover the 32-byte shared secret from an xkem ciphertext using the
// wallet's own decapsulation key.
//
// Parallel to `acegf_decrypt_with_mnemonic`: mnemonic + passphrase unlock
// the wallet's ML-KEM-768 secret key, which is then applied to the Base64
// ciphertext produced by `acegf_encapsulate_for_xkem`.
//
// Returns a C string containing the Base64 shared secret on success, or
// `"error:..."` on failure.
char *acegf_decapsulate_for_xkem(const char *mnemonic,
                                 const char *passphrase,
                                 const char *ciphertext_b64);

// Decrypt with mnemonic (buffer-based version for Flutter FFI)
//
// Two-pass usage:
// 1. First call: pass dummy out_plaintext buffer, out_len = 1
//    - Returns false (0), but out_len is set to required buffer size
// 2. Second call: allocate buffer of size out_len, pass it
//    - Returns true (1) on success, plaintext written to out_plaintext
//
// Returns: 1 (true) on success, 0 (false) on failure or when returning required size
uint8_t acegf_decrypt_with_mnemonic(const char *mnemonic,
                                    const char *passphrase,
                                    const char *ephemeral_pub_b64,
                                    const char *encrypted_aes_key_b64,
                                    const char *iv_b64,
                                    const uint8_t *encrypted_data,
                                    size_t data_len,
                                    uint8_t *out_plaintext,
                                    size_t *out_len,
                                    const char *secondary_passphrase);

// Decrypt with mnemonic (string return version - legacy)
// Returns base64-encoded plaintext on success, or "error:..." on failure
char *acegf_decrypt_with_mnemonic_str(const char *mnemonic,
                                      const char *passphrase,
                                      const char *ephemeral_pub_b64,
                                      const char *encrypted_aes_key_b64,
                                      const char *iv_b64,
                                      const uint8_t *encrypted_data,
                                      size_t data_len);

// Encrypt `plaintext` for a recipient using hybrid X25519 + ML-KEM-768.
//
// Both `recipient_xidentity_b64` and `recipient_xkem_b64` are required —
// there is NO silent fallback to legacy X25519-only encryption. If either
// is missing or malformed the call returns `"error:..."`.
//
// On success returns a C string containing a JSON-encoded
// `HybridEncryptedPayload`. On failure returns a C string prefixed with
// `"error:"`. The caller must free the returned pointer via
// [`acegf_free_string`].
char *acegf_encrypt_for_recipient_pq(const char *recipient_xidentity_b64,
                                     const char *recipient_xkem_b64,
                                     const uint8_t *plaintext,
                                     size_t plaintext_len);

// Decrypt a hybrid encrypted payload (provided as its JSON string form)
// using `mnemonic + passphrase`.
//
// The version field of the payload is checked with strict equality; any
// deviation fails hard (no downgrade to the legacy X25519 path).
//
// On success returns a C string containing the Base64-encoded plaintext.
// On failure returns `"error:..."`. The caller must free the returned
// pointer via [`acegf_free_string`].
char *acegf_decrypt_for_recipient_pq(const char *mnemonic,
                                     const char *passphrase,
                                     const char *payload_json);

// Decrypt with passkey PRF key (buffer-based version for Flutter FFI)
//
// Uses PRF key from WebAuthn Secure Enclave instead of a passphrase.
// The PRF key is fed through Argon2 to derive base_key, then used
// to unseal the mnemonic and perform ECDH decryption.
//
// Two-pass usage (same as acegf_decrypt_with_mnemonic):
// 1. First call: pass dummy out_plaintext buffer, out_len = 1
//    - Returns 0, but out_len is set to required buffer size
// 2. Second call: allocate buffer of size out_len, pass it
//    - Returns 1 on success, plaintext written to out_plaintext
//
// Parameters:
// - mnemonic: ACE-GF mnemonic (C string)
// - prf_key_ptr: PRF output from WebAuthn (raw bytes)
// - prf_key_len: length of PRF key (typically 32 bytes)
// - ephemeral_pub_b64: base64-encoded ephemeral public key
// - encrypted_aes_key_b64: base64-encoded encrypted AES key
// - iv_b64: base64-encoded IV
// - encrypted_data: ciphertext bytes
// - data_len: length of ciphertext
// - out_plaintext: output buffer for plaintext
// - out_len: in/out size parameter
//
// Returns: 1 on success, 0 on failure
uint8_t acegf_decrypt_with_passkey(const char *mnemonic,
                                   const uint8_t *prf_key_ptr,
                                   size_t prf_key_len,
                                   const char *ephemeral_pub_b64,
                                   const char *encrypted_aes_key_b64,
                                   const char *iv_b64,
                                   const uint8_t *encrypted_data,
                                   size_t data_len,
                                   uint8_t *out_plaintext,
                                   size_t *out_len);

// Free a C string allocated by acegf (alias for acegf_free_string)
void acegf_free_cstring(char *ptr);

char *solana_sign_system_transfer(const char *mnemonic,
                                  const char *passphrase,
                                  const char *to_pubkey,
                                  uint64_t lamports,
                                  const char *recent_blockhash);

char *solana_sign_system_transfer_with_secondary(const char *mnemonic,
                                                 const char *passphrase,
                                                 const char *secondary_passphrase,
                                                 const char *to_pubkey,
                                                 uint64_t lamports,
                                                 const char *recent_blockhash);

char *solana_sign_spl_transfer(const char *mnemonic,
                               const char *passphrase,
                               const char *mint,
                               const char *to_wallet,
                               uint64_t amount,
                               const char *recent_blockhash);

char *solana_get_ata_address(const char *wallet, const char *mint);

char *solana_sign_spl_transfer_with_create_ata(const char *mnemonic,
                                               const char *passphrase,
                                               const char *mint,
                                               const char *to_wallet,
                                               uint64_t amount,
                                               const char *recent_blockhash);

char *solana_sign_transaction(const char *mnemonic,
                              const char *passphrase,
                              const char *serialized_tx_base64);

char *vadar_normalize_email(const char *email);

char *vadar_compute_discovery_id(const char *password, const char *normalized_email);

char *vadar_seal_sa2(const char *mnemonic, const char *password, const char *normalized_email);

char *vadar_unseal_sa2(const char *sa2_base64, const char *password, const char *normalized_email);

char *vadar_get_owner_pubkey(const char *password, const char *normalized_email);

char *vadar_sign_registry_update(const char *password,
                                 const char *normalized_email,
                                 const char *discovery_id,
                                 const char *cid,
                                 uint64_t version,
                                 const char *commit);

char *vadar_compute_commit(const char *sa2_base64);

char *evm_sign_type0_transaction(const char *mnemonic,
                                 const char *passphrase,
                                 uint64_t chain_id,
                                 const char *nonce,
                                 const char *gas_price,
                                 const char *gas_limit,
                                 const char *to,
                                 const char *value,
                                 const char *data);

char *evm_sign_legacy_transaction(const char *mnemonic,
                                  const char *passphrase,
                                  uint64_t chain_id,
                                  const char *nonce,
                                  const char *gas_price,
                                  const char *gas_limit,
                                  const char *to,
                                  const char *value,
                                  const char *data);

char *evm_sign_eip1559_transaction(const char *mnemonic,
                                   const char *passphrase,
                                   uint64_t chain_id,
                                   const char *nonce,
                                   const char *max_priority_fee_per_gas,
                                   const char *max_fee_per_gas,
                                   const char *gas_limit,
                                   const char *to,
                                   const char *value,
                                   const char *data);

char *evm_sign_personal_message(const char *mnemonic, const char *passphrase, const char *message);

char *evm_sign_typed_data(const char *mnemonic,
                          const char *passphrase,
                          const char *typed_data_hash);

char *evm_get_address(const char *mnemonic, const char *passphrase);

char *evm_compute_tx_hash(const char *signed_tx);

char *evm_encode_erc20_transfer(const char *to, const char *amount);

char *evm_encode_erc20_approve(const char *spender, const char *amount);

// Get Bitcoin P2WPKH address from mnemonic
// Returns bc1q... (mainnet) or tb1q... (testnet), or "error:..." on failure
char *bitcoin_get_address(const char *mnemonic, const char *passphrase, uint8_t testnet);

// Get Bitcoin Taproot address from mnemonic
// Returns bc1p... (mainnet) or tb1p... (testnet), or "error:..." on failure
char *bitcoin_get_taproot_address(const char *mnemonic, const char *passphrase, uint8_t testnet);

// Sign a Bitcoin transaction (auto-detects P2WPKH vs P2TR from inputs)
// tx_json: JSON string with { version, inputs: [{txid, vout, value, sequence, script_pubkey}], outputs: [{value, script_pubkey}], locktime }
// Returns signed transaction as hex string, or "error:..." on failure
char *bitcoin_sign_transaction(const char *mnemonic,
                               const char *passphrase,
                               const char *tx_json);

// Convert a Bitcoin bech32/bech32m address between mainnet and testnet
// Returns converted address, or "error:..." on failure
char *bitcoin_convert_address_network(const char *address, uint8_t testnet);

// Generate scriptPubKey for any Bitcoin address
// Returns scriptPubKey as hex string, or "error:..." on failure
char *bitcoin_address_to_script_pubkey(const char *address);

// Generate a new REV32 wallet with passphrase
// Returns JSON: { mnemonic, solana_address, evm_address, bitcoin_address, cosmos_address, polkadot_address, xaddress, xidentity }
// or JSON: { error: true, message: "..." }
char *acegf_generate_rev32(const char *passphrase);

char *acegf_generate_rev32_with_secondary(const char *passphrase, const char *secondary_passphrase);

// View REV32 wallet (restore from 24-word mnemonic)
char *acegf_view_wallet_rev32(const char *mnemonic, const char *passphrase);

char *acegf_view_wallet_rev32_with_secondary(const char *mnemonic,
                                             const char *passphrase,
                                             const char *secondary_passphrase);

// Unified wallet view for canonical REV32 mnemonics.
char *acegf_view_wallet_unified(const char *mnemonic, const char *passphrase);

char *acegf_view_wallet_unified_with_secondary(const char *mnemonic,
                                               const char *passphrase,
                                               const char *secondary_passphrase);

// View wallet using PRF key
char *acegf_view_wallet_with_prf(const char *mnemonic,
                                 const uint8_t *prf_key_ptr,
                                 size_t prf_key_len);

// Sign message using PRF key
// Returns base64 signature on success, or "error:..." on failure
char *acegf_sign_message_with_prf(const char *mnemonic,
                                  const uint8_t *prf_key_ptr,
                                  size_t prf_key_len,
                                  const uint8_t *message,
                                  size_t message_len,
                                  uint32_t curve);

// Compute DH shared key using PRF key
// Returns base64-encoded key on success, or "error:..." on failure
char *acegf_compute_dh_key_with_prf(const char *mnemonic,
                                    const uint8_t *prf_key_ptr,
                                    size_t prf_key_len,
                                    const char *peer_pub_b64);

// Decrypt with PRF key (string return version)
// Returns base64-encoded plaintext on success, or "error:..." on failure
char *acegf_decrypt_with_prf(const char *mnemonic,
                             const uint8_t *prf_key_ptr,
                             size_t prf_key_len,
                             const char *ephemeral_pub_b64,
                             const char *encrypted_aes_key_b64,
                             const char *iv_b64,
                             const uint8_t *encrypted_data,
                             size_t data_len);

// Sign EVM Type-0 Transaction using PRF key
char *evm_sign_type0_transaction_with_prf(const char *mnemonic,
                                          const uint8_t *prf_key_ptr,
                                          size_t prf_key_len,
                                          uint64_t chain_id,
                                          const char *nonce,
                                          const char *gas_price,
                                          const char *gas_limit,
                                          const char *to,
                                          const char *value,
                                          const char *data);

char *evm_sign_legacy_transaction_with_prf(const char *mnemonic,
                                           const uint8_t *prf_key_ptr,
                                           size_t prf_key_len,
                                           uint64_t chain_id,
                                           const char *nonce,
                                           const char *gas_price,
                                           const char *gas_limit,
                                           const char *to,
                                           const char *value,
                                           const char *data);

// Sign EVM EIP-1559 Transaction using PRF key
char *evm_sign_eip1559_transaction_with_prf(const char *mnemonic,
                                            const uint8_t *prf_key_ptr,
                                            size_t prf_key_len,
                                            uint64_t chain_id,
                                            const char *nonce,
                                            const char *max_priority_fee_per_gas,
                                            const char *max_fee_per_gas,
                                            const char *gas_limit,
                                            const char *to,
                                            const char *value,
                                            const char *data);

// Sign EVM personal message using PRF key
char *evm_sign_personal_message_with_prf(const char *mnemonic,
                                         const uint8_t *prf_key_ptr,
                                         size_t prf_key_len,
                                         const char *message);

// Sign EVM typed data using PRF key
char *evm_sign_typed_data_with_prf(const char *mnemonic,
                                   const uint8_t *prf_key_ptr,
                                   size_t prf_key_len,
                                   const char *typed_data_hash);

// Get EVM address using PRF key
char *evm_get_address_with_prf(const char *mnemonic,
                               const uint8_t *prf_key_ptr,
                               size_t prf_key_len);

// Sign Solana system transfer using PRF key
char *solana_sign_system_transfer_with_prf(const char *mnemonic,
                                           const uint8_t *prf_key_ptr,
                                           size_t prf_key_len,
                                           const char *to_pubkey,
                                           uint64_t lamports,
                                           const char *recent_blockhash);

// Sign Solana external transaction using PRF key
char *solana_sign_transaction_with_prf(const char *mnemonic,
                                       const uint8_t *prf_key_ptr,
                                       size_t prf_key_len,
                                       const char *serialized_tx_base64);

// Sign Bitcoin transaction using PRF key
char *bitcoin_sign_transaction_prf(const char *mnemonic,
                                   const uint8_t *prf_key_ptr,
                                   size_t prf_key_len,
                                   const char *tx_json);

int32_t acegf_call(const struct ACEGF_Call *call, struct ACEGF_Result *out);

void acegf_free_result(struct ACEGF_Result *result);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ACEGF_H */
